#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php' ;

//echo "\e[0;31;41m fgsdg" ;
//die() ;

$config = include_once 'config.php' ;
\SeeNotEvil\Console\Core\KernelFactory::factory($config)->execute() ;

